repo_url: https://github.com/Interacao-Humano-Computador/2024.1-CBMERJ/tree/main
site_name: CBMERJ - Grupo 7
theme:
  name: material
  language: pt-BR
  features: 
    - toc.integrate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Alternar para modo escuro

    - scheme: slate 
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Alternar para modo claro
  favicon: logo_corpo_de_bombeiros.png
  logo: logo_corpo_de_bombeiros.png
extra:
  extra_css:
  - style.css
copyright: |
  &copy; 2024 - IHC

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences


# Page tree
nav: 
  - Início: index.md
  - Atas:
      - Ata 1: atas/ata_1.md
      - Ata 2: atas/ata_2.md
      - Ata 3: atas/ata_3.md
      - Ata 4: atas/ata_4.md
      - Ata 5: atas/ata_5.md
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao_1.md
      - Apresentação 2: apresentacoes/apresentacao_2.md
      - Apresentação 3: apresentacoes/apresentacao_3.md
      - Apresentação 4: apresentacoes/apresentacao_4.md
      - Apresentação 5: apresentacoes/apresentacao_5.md
  - Planejamento:
      - Heatmap: planejamento/heatmap.md
      - Cronograma: planejamento/cronograma.md
      - Cronograma Realizado: planejamento/CronogramaRealizado.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Processo de Design: planejamento/processo-de-design.md
      - Sites Avaliados: planejamento/sites-avaliados.md
      - Site Escolhido: planejamento/site-escolhido.md
  - Análise de Requisitos I:
      - Perfil do Usuário: analise_requisitos_1/perfil_usuario.md
      - Aspectos Éticos: analise_requisitos_1/aspectos_eticos.md
      - Personas: analise_requisitos_1/personas.md
      - Cenários: analise_requisitos_1/cenarios.md
      - Análise de tarefas: analise_requisitos_1/analise_tarefas.md
  - Análise de Requisitos II:
      - Princípios Gerais de Projeto: analise_requisitos_2/principios_gerais.md
      - Metas de usabilidade: analise_requisitos_2/metas_usabilidade.md
      - Guia de Estilo: analise_requisitos_2/guia_estilo.md
      - Características da plataforma para o projeto: analise_requisitos_2/caracteristica_plat_proj.md
  - Design, Avaliação e Desenvolvimento:
      - Nível 1:
          - Análise de tarefas:
              - Planejamento da Avaliação: design_avaliacao_desenvolvimento/nivel_1/analise_tarefas/planejamento_avaliacao.md
              - Planejamento do relato dos resultados: design_avaliacao_desenvolvimento/nivel_1/analise_tarefas/planejamento_relato_resultados.md
              - Relato dos resultados: design_avaliacao_desenvolvimento/nivel_1/analise_tarefas/relato_resultados.md
          - StoryBoard:
              - Planejamento da Avaliação: design_avaliacao_desenvolvimento/nivel_1/story_board/planejamento_avaliacao.md
              - Planejamento do relato dos resultados: design_avaliacao_desenvolvimento/nivel_1/story_board/planejamento_relato_resultados.md
              - Relato dos resultados: design_avaliacao_desenvolvimento/nivel_1/story_board/relato_resultados.md
              - Storyboards: design_avaliacao_desenvolvimento/nivel_1/story_board/storyboards.md
      - Nível 2:
          - Protótipo de papel:
              - Planejamento da avaliação Protótipo de papel: design_avaliacao_desenvolvimento/nivel_2/prototipo_papel/planejamento_prototipo_papel.md
              - Planejamento do Relato dos resultados do protótipo de papel: design_avaliacao_desenvolvimento/nivel_2/prototipo_papel/planejamento_relato_resultados_prototipo_papel.md
  - Verificação dos artefatos:
      - Verificação de Artefatos - Grupo 8:
          - Planejamento da Verificação: verificacao_artefatos/verificacao_grupo_8/planejamento_verificacao.md
          - Etapa 1:
              - Aviso: verificacao_artefatos/verificacao_grupo_8/etapa_1/aviso.md
          - Etapa 2:
              - Perfil do Usuário: verificacao_artefatos/verificacao_grupo_8/etapa_2/perfil_usuario.md
              - Personas: verificacao_artefatos/verificacao_grupo_8/etapa_2/personas.md
              - Cenários: verificacao_artefatos/verificacao_grupo_8/etapa_2/cenarios.md
              - Análise de tarefas: verificacao_artefatos/verificacao_grupo_8/etapa_2/analise_tarefas.md
          - Etapa 3:
              - Planejamento da Verificação: verificacao_artefatos/verificacao_grupo_8/etapa_3/01_planejamento.md
              - Características Gerais: verificacao_artefatos/verificacao_grupo_8/etapa_3/05_caracteristicas_gerais.md
              - Guia de Estilo: verificacao_artefatos/verificacao_grupo_8/etapa_3/04_guia_de_estilo.md
              - Metas de Usabilidade: verificacao_artefatos/verificacao_grupo_8/etapa_3/03_metas_usabilidade.md
              - Princípios Gerais: verificacao_artefatos/verificacao_grupo_8/etapa_3/02_princípios_gerais.md
          - Etapa 4:
              - Nível 1:
                  - Análise de tarefas: 
                      - Planejamento da Avaliação: verificacao_artefatos/verificacao_grupo_8/etapa_4/nivel_1/analise_tarefas/planejamento_avaliacao.md
                      - Planejamento do Relato dos Resultados: verificacao_artefatos/verificacao_grupo_8/etapa_4/nivel_1/analise_tarefas/planejamento_relato_resultados.md
                      - Relato dos Resultados: verificacao_artefatos/verificacao_grupo_8/etapa_4/nivel_1/analise_tarefas/relato_resultados.md
                  - StoryBoard:
                      - Planejamento da Avaliação: verificacao_artefatos/verificacao_grupo_8/etapa_4/nivel_1/storyboard/planejamento_avaliacao.md
                      - Planejamento do Relato dos Resultados: verificacao_artefatos/verificacao_grupo_8/etapa_4/nivel_1/storyboard/planejamento_relato_resultados.md
                      - Relato dos Resultados: verificacao_artefatos/verificacao_grupo_8/etapa_4/nivel_1/storyboard/relato_resultados.md
                      - Storyboards: verificacao_artefatos/verificacao_grupo_8/etapa_4/nivel_1/storyboard/storyboards.md
            
